### ISSUE TITLE
Raspbian Buster

### ISSUE THREAD

**Issue by svsintel** [lueschem/edi-raspbian#5]
I build the debian buster, do you have a script for building the cross-compilers?

**Comment by lueschem** [comment]
Am I correct that you would like to upgrade [this setup](https://www.get-edi.io/Cross-Compiling-for-Raspbian/) to _Raspbian_ buster? Unfortunately I have not written any scripts to generate the matching Debian/Raspbian cross compiler packages automatically. However, after some reverse engineering I found out that the procedure is not that complicated and I took some notes here: https://github.com/get-edi/raspbian-cross-compiler
I hope that those instructions can be adapted to Buster.
If you take a pure Debian, then all those packages are already present. However, the resulting images/binaries will only work on Raspberry Pi editions that fully support ARMv7-A. For your use case I can not guess whether you would be better off with pure Debian or Raspbian. It could even be a combination like this: A pure Debian rootfs with a kernel that is built from the Raspberry Pi kernel sources and packaged as a proper Debian package.

**Comment by svsintel** [comment]
I would rather use arm64 debian on my RPi4, but I want to share my ML stuff with more non-tech people.  I have updated edi-raspbian for buster, but it fails getting the toolchain.  I will work on creating a cross compiler today.

TASK [apt_setup : Update and upgrade apt.] *************************************
                                                                                                                                                                                                                                                fatal: [raspbian-buster-cross]: FAILED! => {"changed": false, "msg": "Failed to update apt cache."}
 [WARNING]: Could not create retry file '/usr/lib/python3/dist-
packages/edi/plugins/playbooks/debian/base_system/main.retry'.         [Errno
13] Permission denied: u'/usr/lib/python3/dist-
packages/edi/plugins/playbooks/debian/base_system/main.retry'


PLAY RECAP *********************************************************************
raspbian-buster-cross      : ok=6    changed=0    unreachable=0    failed=1   

Error: Command '['sudo', '-u', 'savages', 'ansible-playbook', '--connection', 'lxd', '--inventory', '/home/savages/rpi/edi-raspbian/tmpaemwdmlr/inventory', '--extra-vars', '@/home/savages/rpi/edi-raspbian/tmpaemwdmlr/extra_vars_010_base_system', '/usr/lib/python3/dist-packages/edi/plugins/playbooks/debian/base_system/main.yml']' returned non-zero exit status 2.
For more information increase the log level.

**Comment by greenpdx** [comment]
personal account

**Comment by lueschem** [comment]
Cool - now I understand a bit better your use case.

**Comment by lueschem** [comment]
I just pushed a "buster" branch. I successfully built a buster cross compilation container, cross compiled libssl and booted using that re-compiled library on a Raspberry Pi 1.
I will do some more testing but for those brave enough to help out with testing please use the buster branch and enjoy gcc 8.3!

**Comment by greenpdx** [comment]
GREAT!!  Thank you.  I will test it today.

**Comment by svsintel** [comment]
I am cross compiling opencv,  I get this error.  I have read that it is because python-dev is not installed. But because this is a cross-compile that means that python-dev:armhf is not installed. 

I did a find and I see it for the x86_64 pythons.  
Now when I try to install dependencies, I try (because it keeps asking for more deps, I added more packages). 

sudo apt-get install libpython2-dev:armhf libpython2.7-dev:armhf libc-dev:armhf libc6-dev:armhf libexpat1-dev:armhf linux-libc-dev:armhf libc-dev-bin:armhf libc6:armhf

I get The following packages have unmet dependencies:
 libc6-dev:armhf : Depends: libc6:armhf (= 2.28-10+rpi1) but 2.28-10 is to be installed

This tells me that some packages are installed. I also see that there is a rpi1 tag added. 

where is 
arm-linux-gnueabihf/python2.7/pyconfig.h

/usr/include/python2.7/pyconfig.h:24:12: fatal error: arm-linux-gnueabihf/python2.7/pyconfig.h: No such file or directory
 #  include <arm-linux-gnueabihf/python2.7/pyconfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lueschem** [comment]
Good catch! The -dev packages ask for an exact version match. Therefore I added some additional packages to the repository that edi-raspbian uses.

Can you try again?
Within the container you just have to do a `sudo apt update` and then install the additional packages.

P.S.: This is the advantage of a pure Debian environment like in edi-pi. There the versions will always match.

**Comment by svsintel** [comment]
installed
 libdrm-dev:armhf : Breaks: libdrm-dev (!= 2.4.97-1+rpi1) but 2.4.97-1 is to be installed
 libdrm2:armhf : Depends: libdrm-common:armhf (>= 2.4.97-1+rpi1)
 libgtk-3-0:armhf : Depends: adwaita-icon-theme:armhf

**Comment by svsintel** [comment]
I am sorry that I can not be more helpfull in debugging these problems. 
My goal is to build tensorflow for RPi4 and buster

INFO:root:[GNUPG:] NEWSIG
[GNUPG:] KEY_CONSIDERED A0DA38D0D76E8B5D638872819165938D90FDDD2E 0
[GNUPG:] SIG_ID 8eo3YpOt922uASRdYWvMAo5ZA9w 2019-10-10 1570704681
[GNUPG:] KEY_CONSIDERED A0DA38D0D76E8B5D638872819165938D90FDDD2E 0
[GNUPG:] GOODSIG 9165938D90FDDD2E Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>
[GNUPG:] VALIDSIG A0DA38D0D76E8B5D638872819165938D90FDDD2E 2019-10-10 1570704681 0 4 0 1 8 01 A0DA38D0D76E8B5D638872819165938D90FDDD2E
[GNUPG:] TRUST_UNDEFINED 0 pgp
[GNUPG:] VERIFICATION_COMPLIANCE_MODE 23

INFO:root:Signature check ok!
Error: Package 'qemu-user-static' not found in repository 'http://mirrordirector.raspbian.org/raspbian'.

**Comment by lueschem** [comment]
**With regards to libdrm-dev:armhf:** 

We have again the Raspbian specific +rpi1 version mismatch. I quickly tried to recompile the dependencies without the +rpi1. However, the dependencies are complex and I do not have enough time to dig deeper into that issue. This is why I personally prefer a pure Debian setup. There the dependencies are properly available. If I were you then I would try to compile the packages on an RPi4 (without cross compilation).

**With regards to qemu-user-static:**

I guess you tried this command:
`sudo edi -v lxc configure raspbian-buster-emulated buster-emulated.yml`. I now fixed this issue with the latest commits on edi-raspbian. Thanks for reporting that issue!

**Comment by greenpdx** [comment]
I am willing to help recompile things for you. But I need some instruction on how to or what to do. I find by compiling the kernel and libc with RPi4 -march -mcpu for the 4 I get a 20% increase in speed. on simple CPU bound benchmarks.

**Comment by lueschem** [comment]
OK, this is an interesting result! 20% is quite a big difference.

To get a better cross compilation experience, we have to get exactly the same versions from Raspbian (armhf) and Debian (amd64) when -dev packages are involved. I saw quite a few libraries that come with the +rpi1 version suffix (it would be very nice if Raspbian could get rid of this suffix - for cross compilation it causes a lot of unneeded pain). The easiest way to fix this is probably to rebuild matching amd64 versions of those libraries. Then the libraries for both architectures (armhf/amd64) can be uploaded to the cross compilation repository. I will do some more research as soon as I find time.

**Comment by lueschem** [comment]
I just tried out two possible ways to resolve the "+rpi1 mismatch":

- (Cross)compile the armhf package without the +rpi1 by taking the source code from Debian.
- Compile the amd64 package with the +rpi1 by taking the source code from Raspbian.

Both ways will probably work. The fun part starts when you try to cross compile systemd. I do not know yet how to resolve the cyclic dependency there. I even do not know whether I want to find it out since I can easily do a native build on the Raspbery Pi or even on my notebook (depending on which of the above ways I choose).

**Comment by lueschem** [comment]
For those running into the "+rpi1" version mismatch:

I have described a workaround in [my recent blog post](https://www.get-edi.io/Cross-Compiling-for-Raspbian-Buster/).
