### ISSUE TITLE
Can't build on linux mint 19.1 mate 64 bit

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [lueschem/edi-raspbian#8]
nathan@Dell-latitude-E6510:~/edi-raspbian$ sudo edi -v lxc configure raspbian-buster-cross buster-cross.yml
INFO:root:Load time dictionary:
edi_configuration_name: buster-cross
edi_configure_remote_target: false
edi_create_distributable_image: false
edi_current_display: '0'
edi_current_user_gid: 1000
edi_current_user_group_name: nathan
edi_current_user_host_home_directory: /home/nathan
edi_current_user_name: nathan
edi_current_user_ssh_pub_keys: []
edi_current_user_target_home_directory: /home/nathan
edi_current_user_uid: 1000
edi_edi_plugin_directory: /usr/lib/python3/dist-packages/edi/plugins
edi_edi_version: 1.9.4+u1804
edi_host_ftp_proxy: ''
edi_host_hostname: Dell-latitude-E6510
edi_host_http_proxy: ''
edi_host_https_proxy: ''
edi_host_no_proxy: ''
edi_host_socks_proxy: ''
edi_log_level: INFO
edi_lxd_version: 3.0.3
edi_project_directory: /home/nathan/edi-raspbian
edi_project_plugin_directory: /home/nathan/edi-raspbian/plugins
edi_work_directory: /home/nathan/edi-raspbian

INFO:root:Using base configuration file 'buster-cross.yml'
INFO:root:Using overlay configuration file 'configuration/overlay/buster-cross.global.yml'
INFO:root:Merged configuration:
bootstrap:
  additional_packages:
  - python
  - sudo
  - netbase
  - net-tools
  - iputils-ping
  - ifupdown
  - isc-dhcp-client
  - resolvconf
  - systemd
  - systemd-sysv
  - gnupg
  - dumb-init
  architecture: amd64
  repository: deb http://deb.debian.org/debian buster main
  repository_key: https://ftp-master.debian.org/keys/archive-key-9.asc
documentation_steps: {}
general:
  edi_compression: gz
  edi_required_minimal_edi_version: 1.1.0
  parameters:
    gcc_bootstrap_environment: false
lxc_profiles:
  010_lxc_networking:
    path: lxc_profiles/general/lxc_networking/default_interface.yml
  020_default_root_device:
    path: lxc_profiles/general/default_root_device/default_root_device.yml
  030_suppress_init:
    path: lxc_profiles/general/suppress_init/suppress_init.yml
    skip: true
lxc_templates:
  010_etc_hostname:
    path: lxc_templates/debian/hostname/hostname.yml
  020_etc_hosts:
    path: lxc_templates/debian/hosts/hosts.yml
playbooks:
  010_base_system:
    parameters:
      install_openssh_server: true
    path: playbooks/debian/base_system/main.yml
  040_development_user_facilities:
    path: playbooks/debian/development_user_facilities/main.yml
  050_development_setup:
    parameters:
      enable_cross_development: true
    path: playbooks/development_setup_buster/main.yml
postprocessing_commands: {}
qemu: {}
shared_folders:
  edi_workspace:
    folder: edi-workspace
    mountpoint: edi-workspace

Going to bootstrap initial image - be patient.
INFO:root:Running command: ['debootstrap', '--arch=amd64', '--variant=minbase', '--include=python,sudo,netbase,net-tools,iputils-ping,ifupdown,isc-dhcp-client,resolvconf,systemd,systemd-sysv,gnupg,dumb-init', '--components=main', '--force-check-gpg', '--keyring=/home/nathan/edi-raspbian/tmpkmbxibdj/temp_keyring.gpg', 'buster', '/home/nathan/edi-raspbian/tmpkmbxibdj/rootfs', 'http://deb.debian.org/debian']
I: Retrieving InRelease 
I: Checking Release signature
E: Release signed by unknown key (key id DCC9EFBF77E11517)
Error: Command '['debootstrap', '--arch=amd64', '--variant=minbase', '--include=python,sudo,netbase,net-tools,iputils-ping,ifupdown,isc-dhcp-client,resolvconf,systemd,systemd-sysv,gnupg,dumb-init', '--components=main', '--force-check-gpg', '--keyring=/home/nathan/edi-raspbian/tmpkmbxibdj/temp_keyring.gpg', 'buster', '/home/nathan/edi-raspbian/tmpkmbxibdj/rootfs', 'http://deb.debian.org/debian']' returned non-zero exit status 1.
For more information increase the log level.

**Comment by lueschem** [comment]
Thanks for pointing it out!
It should be fixed now.
